#!/bin/bash

if [ -z "$LIBAUTO_PRIV_USER" ]
then
    echo "Error: The LIBAUTO_PRIV_USER variable is not set."
    exit 1
fi

if [ -z "$LIBAUTO_PATH" ]
then
    echo "Error: The LIBAUTO_PATH variable is not set."
    exit 1
fi

sudo -u "$LIBAUTO_PRIV_USER" -i /bin/bash -c "cd $LIBAUTO_PATH && git pull"

sleep 5    # Allows the user time to see what happened.

reboot

