#!/bin/bash

if [ -z "$AA_CURRICULUM_REPO" ]
then
    echo "Error: The AA_CURRICULUM_REPO variable is not set."
    exit 1
fi

cd "$HOME"

CURRICULUM_DIR="Curriculum"

echo "Deleting old curriculum directory..."
rm -rf "$CURRICULUM_DIR"

echo "Cloning new curriculum repo into" "$HOME"/"$CURRICULUM_DIR"
git clone "$AA_CURRICULUM_REPO" "$CURRICULUM_DIR"
rm -rf "$CURRICULUM_DIR"/.git*

echo "Duplicating the Jupyter notebooks..."
for i in `find "$CURRICULUM_DIR" -name '*.ipynb'`
do
    dir="$(dirname "$i")"
    filename="$(basename "$i")"
    extension="${filename##*.}"
    filename="${filename%.*}"
    cp "$i" "$dir/$filename (Student 1).$extension"
    cp "$i" "$dir/$filename (Student 2).$extension"
    cp "$i" "$dir/$filename (Student 3).$extension"
    cp "$i" "$dir/$filename (Student 4).$extension"
    cp "$i" "$dir/$filename (Student 5).$extension"
    rm "$i"
done

echo 'Done!'

