#!/bin/bash

if ! [ $(id -u) = 0 ]
then
    echo "You must be root to use this script."
    exit 1
fi

if [ -z "$LIBAUTO_PRIV_USER" ]
then
    echo "Error: The LIBAUTO_PRIV_USER variable is not set."
    exit 1
fi

if [ -z "$LIBAUTO_PATH" ]
then
    echo "Error: The LIBAUTO_PATH variable is not set."
    exit 1
fi

sudo -u "$LIBAUTO_PRIV_USER" -i /bin/bash -c "cd $LIBAUTO_PATH && git pull"
reboot

