#!/bin/bash

if ! [ $(id -u) = 0 ]
then
    echo "You must be root to use this script."
    exit 1
fi

if [ -z "$1" ]
then
    echo "No password specified on command line."
    exit 1
fi

if [ -z "$2" ]
then
    echo "No system username specified on command line."
    exit 1
fi

PASSWD="$1"
USERNAME="$2"

echo -e "$PASSWD""\n""$PASSWD" | passwd "$USERNAME"

exit $!
