#!/bin/bash

if ! [ $(id -u) = 0 ]
then
    echo "You must be root to use this script."
    exit 1
fi

sync

# Change to the `libauto` directory.
scriptdir="$(dirname $(realpath "$0"))"
cd "$scriptdir"/../../../..
echo 'Starting in directory' $(pwd) 'as user' $(whoami)

# Make sure X is running.
while ! xset q &>/dev/null
do
    echo 'Waiting for X Server ...'
    sleep 0.3
done

# Disable screensaver and screen-off-power-savings.
xset -dpms
xset s off

# Run the startup demo program and play the boot video.
python3 auto/services/scripts/demos/demo_car.py &
DEMO_PID=$!
fbcp &
FBCP_PID=$!
omxplayer -b auto/resources/videos/boot_up_video.mp4
kill $FBCP_PID
wait $FBCP_PID || true
wait $DEMO_PID

# Run all migrations.
for migration in "$scriptdir"/rpi_b3_b4_migrations/*
do
    "$migration"
done

sync

# Run all the services.
exec python3 auto/services/run_all.py "$@"

